services:
    app-backend:
        build: 
          context: ./
          dockerfile: ./deploy/Dockerfile_python
        image: reignbreaker_api
        container_name: api_backend
        restart: always
        ports:
            - 5000:5000
    app-frontend:
        build:
          context: ./
          dockerfile: ./deploy/Dockerfile_nginx
        image: reignbreaker_nginx
        container_name: web_frontend
        restart: always
        ports:
            - 80:80
        expose:
            - "80"