name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push nginx Docker image
        with:
          image: mmcmunigle/reignbreakers_nginx
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/Dockerfile_nginx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push flask api Docker image
        with:
          image: mmcmunigle/reignbreakers_api
          tags: latest
          registry: docker.io
          dockerfile: ./deploy/Dockerfile_python
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
